<?php

namespace ContainerKnQ3jf7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAboutControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\about\AboutController' shared autowired service.
     *
     * @return \App\Controller\about\AboutController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/about/AboutController.php';

        $container->services['App\\Controller\\about\\AboutController'] = $instance = new \App\Controller\about\AboutController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\about\\AboutController', $container));

        return $instance;
    }
}
