<?php

namespace ContainerKnQ3jf7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ProjectManager' shared autowired service.
     *
     * @return \App\Services\ProjectManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ProjectManager.php';

        return $container->privates['App\\Services\\ProjectManager'] = new \App\Services\ProjectManager();
    }
}
