<?php

namespace ContainerSVV1w8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__SHG4GCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..sHG4GC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..sHG4GC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\home\\HomeController::addEmail' => ['privates', '.service_locator.5pDFwFy', 'get_ServiceLocator_5pDFwFyService', true],
            'App\\Controller\\home\\HomeController::sendNewsletter' => ['privates', '.service_locator.SAesO7c', 'get_ServiceLocator_SAesO7cService', true],
            'App\\Controller\\project\\ProjectController::showProjects' => ['privates', '.service_locator..ye3FAm', 'get_ServiceLocator__Ye3FAmService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\home\\HomeController:addEmail' => ['privates', '.service_locator.5pDFwFy', 'get_ServiceLocator_5pDFwFyService', true],
            'App\\Controller\\home\\HomeController:sendNewsletter' => ['privates', '.service_locator.SAesO7c', 'get_ServiceLocator_SAesO7cService', true],
            'App\\Controller\\project\\ProjectController:showProjects' => ['privates', '.service_locator..ye3FAm', 'get_ServiceLocator__Ye3FAmService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\home\\HomeController::addEmail' => '?',
            'App\\Controller\\home\\HomeController::sendNewsletter' => '?',
            'App\\Controller\\project\\ProjectController::showProjects' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\home\\HomeController:addEmail' => '?',
            'App\\Controller\\home\\HomeController:sendNewsletter' => '?',
            'App\\Controller\\project\\ProjectController:showProjects' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
