<?php

namespace ContainerSVV1w8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SAesO7cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SAesO7c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SAesO7c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'newsletterRepository' => ['privates', 'App\\Repository\\NewsletterRepository', 'getNewsletterRepositoryService', true],
        ], [
            'newsletterRepository' => 'App\\Repository\\NewsletterRepository',
        ]);
    }
}
