<?php

namespace ContainerSVV1w8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbacksControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\feedbacks\FeedbacksController' shared autowired service.
     *
     * @return \App\Controller\feedbacks\FeedbacksController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/feedbacks/FeedbacksController.php';

        $container->services['App\\Controller\\feedbacks\\FeedbacksController'] = $instance = new \App\Controller\feedbacks\FeedbacksController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\feedbacks\\FeedbacksController', $container));

        return $instance;
    }
}
