<?php

namespace ContainerSVV1w8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\home\HomeController' shared autowired service.
     *
     * @return \App\Controller\home\HomeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/home/HomeController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/TokenGenerator.php';

        $container->services['App\\Controller\\home\\HomeController'] = $instance = new \App\Controller\home\HomeController($container->load('getSession_FlashBagService'), ($container->services['swiftmailer.mailer.default'] ?? $container->load('getSwiftmailer_Mailer_DefaultService')), new \App\Services\TokenGenerator());

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\home\\HomeController', $container));

        return $instance;
    }
}
