<?php

namespace ContainerSVV1w8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectIdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ProjectId' shared autowired service.
     *
     * @return \App\Services\ProjectId
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/ProjectId.php';

        return $container->privates['App\\Services\\ProjectId'] = new \App\Services\ProjectId();
    }
}
