<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI9SHz70\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI9SHz70/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI9SHz70.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI9SHz70\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI9SHz70\App_KernelDevDebugContainer([
    'container.build_hash' => 'I9SHz70',
    'container.build_id' => '1cd2d194',
    'container.build_time' => 1601373000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI9SHz70');
