<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnQ3jf7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnQ3jf7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKnQ3jf7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKnQ3jf7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKnQ3jf7\App_KernelDevDebugContainer([
    'container.build_hash' => 'KnQ3jf7',
    'container.build_id' => '4b9504d6',
    'container.build_time' => 1601297251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnQ3jf7');
